# Copyright (c) 2024 Goodix
# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: goodix-ble

  remotes:
    - name: goodix-ble
      url-base: https://github.com/goodix-ble
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  self:
    path: goodix
    west-commands: scripts/west-commands.yml

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
      import: true

    - name: gr5525_sdk
      repo-path: GR5525.SDK
      remote: goodix-ble
      revision: master
      path: goodix/ble_sdk/gr5525/GR5525.SDK

